name: "AwesomeTemplate"
description: "A template to start everyone off with a cool site!"
url: "https://oskikiboy.me/AwesomeTemplate"
keywords: "cool, Awesome, Jekyll, HTML, template, easy, github"
class: "HTML template"
icon: "/assets/img/icon.png"