name: 'Awesome<span style="font-weight:300;">Template</span>'
meta-name: 'AwesomeTemplate'
description: 'A template to start everyone off with a cool site!'
url: 'https://oskikiboy.me/AwesomeTemplate'
keywords: 'cool, Awesome, Jekyll, HTML, template, easy, github'
class: 'HTML template'
icon: '/assets/img/icon.png'
meta-icon: '/assets/img/icon.png'
